print("I WANNA EAT")
print("I NEED FOOD")
print("I WANNA EAT")
print("I NEED FOOD")
print("I WANNA EAT")
print("I NEED FOOD,I WANNA EAT")
print("I NEED FOOD, I WANNA EAT")
print("I NEED FOOD",I WANNA EAT")
print("I NEED FOOD")
